김기현-백엔드-5주차 장고 DRF과제
likelion-Inha-12/kihyunnn pull request #7
Opened 2024-05-07 13:22 UTC by kihyunnn

키워드 과제 : 

https://kihyunnnnn.tistory.com/4

![DELETE](https://github.com/likelion-Inha-12/kihyunnn/assets/142724910/fda033f3-efeb-462a-b5f8-049f8b501d62)

<delete 호출>

![GET](https://github.com/likelion-Inha-12/kihyunnn/assets/142724910/694ec739-bb7e-4af2-b863-3646249373cb)

<Get 호출>

![POST](https://github.com/likelion-Inha-12/kihyunnn/assets/142724910/8ef7430d-320b-4322-a551-21eee4c594af)

<Post 호출>

2024-05-07 13:24 UTC, kihyunnn commented
gitignore 처음 하기전에 올라가있어서 그런 것 같아서, 다음 실습 때 처음에 깃허브에서 파일 삭제한 후에 pull하고 다음 과제 때는 gitignore 제대로 적용해서 제출하겠습니다!

2024-05-07 13:35 UTC, kseysh commented
아래 참고해서 삭제 이후에 다시 Push 해보세요!
**[[참고한 블로그]](https://tychejin.tistory.com/231)**
<img width="817" alt="image" src="https://github.com/likelion-Inha-12/gayo73/assets/69035864/cf81a73f-2017-4bc4-8953-f99647a3e587">

2024-05-08 04:13 UTC, kseysh requested changes
`__pycache__` 한 번 지워보시고 다시 요청주셔요~!

2024-05-08 06:30 UTC, kihyunnn commented
깃 캐시 삭제 완료했습니다!

2024-05-08 07:05 UTC, kseysh approved these changes
기존에 있던 캐시까지 잘 삭제해주셨네요~ 고생하셨습니다!

2024-05-13 10:17 UTC, merged